name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Ejecutar en Mac

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build

      - name: Run Tests
        run: dotnet test

  deploy:
    runs-on: macos-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Server
        run: |
          echo "Desplegando aplicación..."
          # Aquí iría el comando para desplegar la aplicación, por ejemplo, usando un script.
